version: "3.9"
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: node-complete
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./data/db
        target: /var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8090:8080"
    restart: always
  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - "3090:3000"
    environment:
      MONGO_URL: mongodb+srv://admin:Qwer1234@cluster0.ahwdz.mongodb.net/test
    volumes:
      - type: bind
        source: ./data/mongodb
        target: /data/db
